order-service:
  build: ./order-service
  container_name: order-service
  ports:
    - "3002:3002"
  environment:
    DB_HOST: postgres
    DB_PORT: 5432
    DB_USER: order_service
    DB_PASSWORD: password
    DB_NAME: orders_db
  depends_on:
    - postgres
